version: '3'

tasks:
  run:
    cmds:
      - jupyter notebook

  build:
    - jupyter nbconvert --to html --TagRemovePreprocessor.remove_cell_tags='{"hide_code"}' Showcase.ipynb

  install:
    cmds:
      - pip install jupysql --break-system-packages

  populate-db:
    internal: true
    cmds:
      - |
        cat << EOF | sqlite3 showcase-{{.DBNAME}}.db
        CREATE TABLE users (id serial primary key, email varchar(255), name varchar(255));
        INSERT INTO users (id, email, name) VALUES(1, '{{.EMAIL}}', '{{.USERNAME}}');
        EOF

  populate:
    cmds:
      - task: populate-db
        vars: { DBNAME: "database1", EMAIL: "christoph@unexist.dev", USERNAME: "unexist" }
      - task: populate-db
        vars: { DBNAME: "database2", EMAIL: "christoph@unexist.dev", USERNAME: "unexist" }

